### ISSUE TITLE
Readme to be added.

### ISSUE THREAD

**Issue by ImAnshuJoshi** [XDRAGON2002/iiit-gram#1]
Hey @XDRAGON2002 , I would like to add readme to this repository . Can you assign this to me?

**Comment by XDRAGON2002** [comment]
Hi @ImAnshuJoshi I had been inactive for the last week due to some prior commitments hence couldn't get the repo setup, but I've made some time and have setup the README and CONTRIBUTING files as well, thanks for the helping gesture but as the maintainer of this repository its my responsibility to add the README.
